### PR TITLE
Support customized data

### PR DESCRIPTION
**Pull request by roderickhsiao**
#75 

Not sure this approach is preferred, but this PR add the ability to pass down customized `emojiData` (where we can have separated package to generate international emoji data).

Just like what we have now, the English version one will always be shipped with the package, while users are able to pass overridden data if needed.

```js
import frEmojiData from 'emoji-button/locale-data/fr';
const emojiButton = new EmojiButton({
  emojiData: frEmojiData
});
```

One part of the code doesn't seems to be used anywhere, or perhaps I miss something? 
https://github.com/joeattardi/emoji-button/blob/master/src/emojiArea.ts#L28-L35

Let me know how you think :) Happy to help generate those international emoji data if needed
https://github.com/unicode-org/cldr/tree/master/common/annotations

### CODE REVIEW

**Comment by CyrilKrylatov** [comment]
Nicely done!

I hope this will be merged for a full i18n support!

**Comment by roderickhsiao** [comment]
Interesting notes, for Tinder's web usage, our top 10 countries using emoji keyboard, only US (2), UK (7) is using English, all others are non-English speaking countries. Hence will be nice if we can support i18n search :)

Totally happy to discuss more if this is not the direction like. @joeattardi

**Comment by joeattardi** [comment]
Sorry for the inaction on this - I have been distracted lately :) will take a look at this PR tonight!

**Comment by joeattardi** [comment]
@roderickhsiao That block of code you highlighted does some preprocessing of the emoji data. For this to work fully I'll need to move that processing into the EmojiButton class itself so that it has access to the emoji data option that was passed in. This unfortunately means that the processing will have to be done for every `EmojiButton` instance - I had the logic outside of the class so that it only was done once across the page. I'll see what I can come up with - this PR is a great start. Thanks!

**Comment by roderickhsiao** [comment]
Thank you for the details! Let me know if anything. I can help with :)

**Comment by joeattardi** [comment]
I think I've got it working, now I just need to write some tests and documentation. Feel free to grab the master branch and check it out!

**Comment by roderickhsiao** [comment]
Tested on master, it looks nice!

Many thanks for the support (also fixing my PR lint error lol)

Screen Shot 2020-11-23 at 11 54 21 PM

p.s. I created a package for the locale data https://github.com/roderickhsiao/emoji-button-locale-data from CLDR `annotations` and `annotationsDerived` based on your English text structure. Some emoji translation are missing but should be workable.

**Comment by joeattardi** [comment]
Nice! Thanks for publishing that package - I will link to it in the documentation.

**Comment by roderickhsiao** [comment]
If we could get a new version will be nice :) tried to delight our user before Christmas, but no rush at all

**Comment by joeattardi** [comment]
I should have some time this evening to work on this. Will let you know!

**Comment by roderickhsiao** [comment]
Thank you a tons

**Comment by joeattardi** [comment]
This is in now! I just released v4.6.0 which has the custom data support. Documentation site has been updated as well! Let me know if you run into any issues.

Thanks again for publishing the package with the emoji translations!

**Comment by tinder-rhsiao** [comment]
Thank you! Tested multiple languages and it looks good :)) 🌏 

ezgif com-gif-maker

**Comment by joeattardi** [comment]
Looks great!

**Pull request merged**
