### PR TITLE
Make the project more modern!

### PR DESCRIPTION
**Pull request by Justsnoopy30**
Also has a few cross-platform fixes, and a build test fix.

### CODE REVIEW

**Comment by joeattardi** [comment]
What exactly is the motivation for this change?

**Comment by Justsnoopy30** [comment]
Which change specifically?

**Comment by joeattardi** [comment]
The whole PR I guess. What do you mean by "more modern" exactly?

**Comment by Justsnoopy30** [comment]
Compile as a modern ES module, target the latest ES syntax, use SVG's instead of PNG's for twemoji because they don't lose quality when being scaled and they're smaller, make the build work on windows, and fix build error in emoji.test.ts.

**Comment by joeattardi** [comment]
Cool! Thanks. Question. When it's compiled into an ES module will people still be able to pull it in via a simple script tag, or is a bundled needed?

**Comment by Justsnoopy30** [comment]
In today's browsers, anyone can able to import it with `import EmojiButton from './path/to/emoji-button.js';` in a module (script loaded with type=module), without a bundler at all.

**Comment by joeattardi** [comment]
Didn't know ES module support had landed in all modern browsers! I need to pay more attention to this stuff 😀 I'll take a look at the PR more this evening. 

Thank you!

**Comment by Justsnoopy30** [comment]
You're welcome!

**Comment by Justsnoopy30** [comment]
Oops, I missed two more usages of emoji.parse() that weren't using the options to get an SVG, so in some places it is still requesting PNG. I'll have a commit in a moment to fix that...

**Comment by Justsnoopy30** [comment]
Fixed.

**Comment by Justsnoopy30** [comment]
@joeattardi Is this gonna get merged soon?

**Comment by joeattardi** [comment]
Will try to get to it this week. Lots going on right now!

**Comment by Justsnoopy30** [comment]
Okay!

**Comment by joeattardi** [comment]
Hi, sorry for the long delay, still haven't forgotten about this PR. Been super busy.

**Comment by Justsnoopy30** [comment]
No problem.

**Pull request merged**
